[project]
name = "GameGoly"
version = "2025.0.0"
description = "Web app to play gamegoly"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
	{ name = "laniavea", email = "laniavea@yahoo.com" }
]
requires-python = ">=3.13"
dependencies = [
	"fastapi>=0.118.3",
	"uvicorn>=0.40.0",
]

[project.optional-dependencies]
dev = [
  "ruff",
  "mypy",
  "isort"
]

[build-system]
requires = ["setuptools>=80", "wheel"]
build-backend = "setuptools.build_meta"
