[field]
title = "GameGoly 2025"
base_dice = "1,6 1,6"
# TODO: Make link autogen from config params
help_info = [
	"{{Основная идея}}GameGoly посвящена прохождению игр, вышедших в 2025 году в сервисе steam. Настолка играется с использованием приложения и сервиса steamdb дефолтной ссылке - см прошлые версии. .\nВсе модификаторы, полученные здесь, следует добавить в steamdb поиск. Порядок тегов определяется по расширенному виду тегов в steam, а не в steamdb!",
	"{{Порядок хода}}1) Передвижение по полю (бросок 2x кубиков d6, если нету особых условий)\n2) Выбор тегов (нажать на клетку, посмотреть число игр по каждому из тегов и просуммировать их, затем бросить случайное число от 1 до суммы и этим определить единственный тег)\n3) Выбор игры (выбрать в поиске steamdb основной выпавший тег, добавить дополнительные модификаторы если есть и выбрать случайную из игр, используя сгенерированное число\n4) Выбор использованный модификаторов\n 5) Прохождение игры (ну или дроп)",
	"{{Бросок кубиков}}Основным способом передвижением по полю явяeтся бросок 2x шестигранных кубиков, их число и цифры на них могут быть изменены особыми условиями. Если кубика два, то существуют 6 дополнительных модификаторов на игру из-за броска кубика.\n1) В случае выпадения дубля - игроку добавляется доп.тег.\n2) Если сумма кубов равна 6, то игрок крутит дополнительный модификатор - спешл.\n3) Если сумма кубов равна 10, то игрок добавляет себе спешл.\n4) Если абсолютная разница между значениями кубиков 3 и больше, то добавляется перевод половины\n5) Если сумма кубиков равна 2, то добавляются 2 спешла\n6)Если сумма больше 10, то добавляется 1 геймплейный тег, 1 стилистический",
	"{{Выбор тегов}}После заверешения передвижения, на клетке может быть несколько условий для игры, если для одного условия существует несколько возможных вариантов, то игрок обязан использовать только один, например для поля Tactic. Для совершения выбора игрок должен записать число игр из steamdb для каждого из вариантов и просуммировать их от большего к меньшему, затем выкинуть число от 1 до суммы. Та область на которую упало число и есть итоговый выбор.\nПример: Тег А - 10 игр, Тег Б - 15 игр, Тег В - 11 игр. Ролл от 1 до 36 - 20. Следовательно будет браться тег В. 15 (Тег А) < ролл < 26 (Тег А + Тег В)",
	"{{Выбор игры}}Если итоговое условие определено или клетка не требует такого, то дальше игрок на любой клетке (кроме спешл), добавляет модификаторы для поиска в steamdb (доп.теги и другие условия). После этого steamdb покажет итоговое число игр, подходящих условию. Далее производится ролл от 1 до указанного числа, таким образом выбирается игра. Игрок, если может, то он способен перенести половину, для этого надо разделить число всех игр на 2 (округлять в меньшую) и прибавить или убавить это число к полученному роллу.",
	"{{Прохождение игры}}Каждый круг игроку начисляется один дроп, который можно использовать и завершить ход. В случае дропа без доступных дропов игрок отправляется в тюрьму без прохождения круга",
	"{{Рероллы}}Игрок может реролльнуть игру если:\n1) Если основной тег не находятся в топ-10 на steam странице (или в первой половине если тегов меньше 14)\n2) Если игра противоречит его моральным принципам (gore, сексуальный контент, gaysex и т.п.)\n3) Если игра - симулятор, MMO, пустышка, скам-игра, текстовый квест, ферма, настолка, бесконечная или ой-извините + denuvo(нет в свободном доступе)\n4) Если альтерантивы для игры недоступны (перенос половины и т.п. в т.ч. игры из зоны)",
	"{{Рероллы 2}}Если 10 игр подряд были реролльными, то игрок начинает убирать сначала спешлы, потом доп.теги по 5 доп. рероллов на каждый. Если все убрано, то игрок просто роллит игру по основному тегу и выбирает любую игру между выпавшей и 10 соседними (+11 если half-move), далее он удаляет все доп.теги и спешлы, которые применимы к этой игре",
	"{{Тюрьма}}Если игрок попадает в тюрьму, то его максимальный рейтинг - 85%. Далле игрок роллит дополнительный тег, используя кнопку слева, и играет в случайную игру. Если игра - кал и игрок ее хочет дропнуть, то без проблем - реролл тега -> реролл игры.",
	"{{ТОП-100}}При нахождении на клетке ТОП-100 игрок роллит случайную игру из первых 100 без условий (если нет доп.тега или спешела, меняющие эти условия)",
	"{{Спешл}}Если игрок получает спешл во время совершения броска кубиков, то его необходимо применить к следующей игре или ходу. Если игрок по результатам спешла остается на данной клетке, то игрок выбирает ЛЮБУЮ игру, которую он хочет пройти или роллит по доп.тегам (если они есть и есть желание), а полученное действие необходимо выполнять со следующего хода",
	"{{Зона}}Зона выбора игрока начинается с 1 и расширяется каждые 2 круга (1, 3, 5..) вплоть до 3 увелечений с каждой из сторон. Зона позволяет выбирать в том числе и в перенесенных случайных значениях. Игра может быть рерольнута, если на конкретно выпавшем значение основной тег не представлен, однако реролл по отсуствтвию альтернативы теперь должен быть применим и к игра внутри зоны",
]

[[lists]]
name = "Дополнительный геймплейный тег"
elements = [
	"Simulator",
	"Racing",
	"Clicker",
	"Open world",
	"Resource management",
	"Dungeon crawler",
	"Hack and slash",
	"Hidden object",
	"Survival",
	"Building",
	"Walking simulator",
	"Beat em up",
	"Side scroller",
	"Stealth",
	"RTS",
	"RTT",
	"Dating sim",
	"Card battler",
	"Bullet hell",
	"Difficult",
	"Visual novel",
	"Immersive sim",
	"Live sim",
	"Tower defence",
	"Physics",
]

[[lists]]
name = "Дополнительный стилистический тег"
elements = [
	"3D",
	"2D",
	"Magic",
	"Sci-fi",
	"Female protagonist",
	"Mystery",
	"Dark",
	"Cute",
	"Character customization",
	"Realistic",
	"Historical",
	"Emotional",
	"Detective",
	"Violent",
	"Investigation",
	"Anime",
	"Lore-rich",
	"Romance",
	"Cyberpunk",
	"Gore",
	"Thriller",
	"Fantasy",
	"Funny",
	"Pixel graphics",
	"Dark fantasy",
]

[[lists]]
name = "Карточка спешл"
elements = [
	"D4 для следующего хода",
	"Игрок перемещается на следующую клетку с рандомной игрой",
	"Игрок попадает в тюрьму",
	"(При выборе следующей случ. игры) игра с Early Access",
	"(При выборе следующей случ. игры) Ролится ретинг от 80 до 98, к этому числу добавляется +- 2. Это границы рейтинга",
	"(При выборе следующей случ. игры) Следующая игра должна иметь тег визуальная новелла",
	"(При выборе следующей случ. игры) Должно быть не менее 500 отзывов или 1000 фолловеров(если не найдено)",
	"(При выборе следующей случ. игры) Может быть хоть 0 фолловеров",
	"(При выборе следующей случ. игры) Минимальный рейтинг - 85",
	"Игрок получает 1 бесплатный дроп",
	"Игрок бросает только один куб на следующий ход",
	"(При выборе следующей случ. игры) Игрок может выбрать любую из 6 рядом стоящих игр",
	"(При любом выборе случ. игры) Игрок может перевести число игры в другую половину: наприимер выпало 690 из 700 игр, можно превратить в 11",
	"(При выборе следующей случ. игры) Игрок выбирает любую игру из первых 100 по рейтингу",
	"(При выборе следующие случ. игры) Следующая игра должна иметь японскую озвучку, которая должна быть использована",
	"(При выборе следующей случ. игры) Следующая игра должна иметь перевод на русский, предпочтительно озвучкой",
	"(При выборе следующей случ. игры) Следующая игра должна быть частью какой-либо франшизы в т.ч. кино, аниме и т.п.",
	"(При выборе следующей случ. игры) Ролится случайное число от 1 до 12 и умножается на 5. Это и +- 5 долларов - цена следующей игры",
	"Следующие кубики - 0, 0. Во время второго ролла выбирается любая игра, подходящая под условия клетки",
	"3 следующих случайных игры: рамка выбора расширяется на +1 справа от выпавшего значения",
	"На 3 следующих случайных игры: рамка выбора расширяется на +1 слева от выпавшего значения",
	"На 3 следующих случайных игры: рамка выбора расширяется на +2 от выпавшего значения",
	"(При выборе следующей случ. игры) Следующая игра должна быть создана на unreal engine",
	"(При выборе следующей случ. игры) Число отзывов больше 2000",
	"(При выборе следующей случ. игры) Следующая игра должна иметь полную поддержку контроллера",
]

[[conditions]]
id = 1
rule = "roll_list(Дополнительный геймплейный тег)"

[[conditions]]
id = 2
rule = "roll_list(Дополнительный стилистический тег)"

[[conditions]]
id = 3
rule = "roll_list(Карточка спешл)"

[[conditions]]
id = 4
rule = "spawn_conditions(3, 3)"

[[conditions]]
id = 5
rule = "spawn_conditions(3, 2)"

[[conditions]]
id = 6
rule = "change_value(half-move, +1)"


[[events]]
state = "cubes{=}"
condition_id = 1

[[events]]
state =  "cubes{sum(6)}"
condition_id = 3

[[events]]
state =  "cubes{sum(10)}"
condition_id = 3

[[events]]
state =  "cubes{sum(2)}"
condition_id = 4

[[events]]
state =  "cubes{sum(>10)}"
condition_id = 5

[[events]]
state =  "cubes{diff(>2)}"
condition_id = 6

[[events]]
state =  "cubes{diff(3)}"
condition_id = 2

[[tiles]]
pos = 1
title = "Старт (ТОП-100)"
description = "Ролл производится из лучших 100 игр"
rules = ["(Конкретные игры)TOP-100 по steamdb рейтингу"]
color = "203, 65, 36"
condition_id = 7

[[tiles]]
pos = 2
title = "Point & Click"
description = "Ролл производится по одному из двух тегов: Point & Click или Exploration"
rules = ["(Теги)Point&Click, Exploration"]
color = "181,214,168"
condition_id = 5

[[tiles]]
pos = 3
title = "Доп. гейм. теги"
description = "Ролл производится по случайному дополнительному тегу"
rules = ["(Теги)Один из дополнительных геймплейных тегов"]
color = "193, 122, 160"
condition_id = 6

[[tiles]]
pos = 4
title = "Доп. спец. теги"
description = "Ролл производится по случайному дополнительному тегу"
rules = ["(Теги)Один из дополнительных специальных тегов"]
color = "193, 122, 160"
condition_id = 6

[[tiles]]
pos = 5
title = "FPS or shooter"
description = "Ролл производится по одному из двух тегов: FPS или Shooter"
rules = ["(Теги)FPS, shooter"]
color = "105, 168, 79"
condition_id = 6

[[tiles]]
pos = 6
title = "Случайная игра"
description = "Ролится случайны рейтинг по распределению (диапазон рейтинга игры - шанс): 100-80% - 60%, 79-70% - 20%, 69-50 - 10%, 49-.. - 10%. Если игр больше чем 1000, то равномерно ролится одно значение из выпавшего диапазона. По итоговому рейтингу роллится игра"
rules = ["(Рейтинг)Полученный рейтинг"]
color = "230, 183, 174"
condition_id = 6

[[tiles]]
pos = 7
title = "FPS or shooter"
description = "Ролл производится по одному из двух тегов: FPS или Shooter"
rules = ["(Теги)FPS, shooter"]
color = "105, 168, 79"
condition_id = 6

[[tiles]]
pos = 8
title = "Point & Click"
description = "Ролл производится по одному из двух тегов: Point & Click или Exploration"
rules = ["(Теги)Point&Click, Exploration"]
color = "181,214,168"
condition_id = 5

[[tiles]]
pos = 9
title = "Доп. спец. теги"
description = "Ролл производится по случайному дополнительному тегу"
rules = ["(Теги)Один из дополнительных специальных тегов"]
color = "193, 122, 160"
condition_id = 6

[[tiles]]
pos = 10
title = "Спешл"
description = "Ролл производится или по правилам тюрьма, или по правилам ТОП-100 (в зависимости от того, как игрок попал на клетку)"
rules = ["(Конкретные игры)Любая на выбор игрока"]
color = "179, 94, 5"
condition_id = 6

[[tiles]]
pos = 11
title = "Тюрьма / ТОП-100"
description = "Производится ролл модификатора, далее, если игрок остается на клетке, то он выбирает самостоятельно каким-либо образом игру и проходит ее. Модификатор применяется к следующему ходу"
rules = ["(Тюрьма)См. правила", "(Конкретные игры)TOP-100 по steamdb рейтингу"]
color = "203, 65, 36"
condition_id = 6

[[tiles]]
pos = 12
title = "Доп. спец. теги"
description = "Ролл производится по случайному дополнительному тегу"
rules = ["(Теги)Один из дополнительных специальных тегов"]
color = "193, 122, 160"
condition_id = 6

[[tiles]]
pos = 13
title = "Доп. гейм. теги"
description = "Ролл производится по случайному дополнительному тегу"
rules = ["(Теги)Один из дополнительных геймплейных тегов"]
color = "193, 122, 160"
condition_id = 6

[[tiles]]
pos = 14
title = "Horror"
description = "Ролл производится по одному из следующих тегов: Horror, Psychological Horror или Survival Horror"
rules = ["(Теги)Horror, Psychological Horror, Survival Horror"]
color = "190,143,0"
condition_id = 5

[[tiles]]
pos = 15
title = "Jumper"
description = "Ролл производится по одному из следующих тегов: Platformer, 3d Platformer или 2d Platformer"
rules = ["(Теги)Platformer, 3d Platformer, 2d Platformer"]
color = "126,95,0"
condition_id = 5

[[tiles]]
pos = 16
title = "Случайная игра"
description = "Ролится случайны рейтинг по распределению (диапазон рейтинга игры - шанс): 100-80% - 60%, 79-70% - 20%, 69-50 - 10%, 49-.. - 10%. Если игр больше чем 1000, то равномерно ролится одно значение из выпавшего диапазона. По итоговому рейтингу роллится игра"
rules = ["(Рейтинг)Полученный рейтинг"]
color = "230, 183, 174"
condition_id = 6

[[tiles]]
pos = 17
title = "Horror"
description = "Ролл производится по одному из следующих тегов: Horror, Psychological Horror или Survival Horror"
rules = ["(Теги)Horror, Psychological Horror, Survival Horror"]
color = "190,143,0"
condition_id = 5

[[tiles]]
pos = 18
title = "Jumper"
description = "Ролл производится по одному из следующих тегов: Platformer, 3d Platformer или 2d Platformer"
rules = ["(Теги)Platformer, 3d Platformer, 2d Platformer"]
color = "126,95,0"
condition_id = 5

[[tiles]]
pos = 19
title = "Спешл"
description = "Ролл производится или по правилам тюрьма, или по правилам ТОП-100 (в зависимости от того, как игрок попал на клетку)"
rules = ["(Конкретные игры)Любая на выбор игрока"]
color = "179, 94, 5"
condition_id = 6

[[tiles]]
pos = 20
title = "Доп. гейм. теги"
description = "Ролл производится по случайному дополнительному тегу"
rules = ["(Теги)Один из дополнительных геймплейных тегов"]
color = "193, 122, 160"
condition_id = 6

[[tiles]]
pos = 21
title = "ТОП-100 (21)"
description = "Ролл производится из лучших 100 игр"
rules = ["(Конкретные игры)TOP-100 по steamdb рейтингу"]
color = "203, 65, 36"
condition_id = 7

[[tiles]]
pos = 22
title = "Puzzle"
description = "Ролл производится по тегу Puzzle"
rules = ["(Теги)Puzzle"]
color = "56, 117, 28"
condition_id = 6

[[tiles]]
pos = 23
title = "Доп. гейм. теги"
description = "Ролл производится по случайному дополнительному тегу"
rules = ["(Теги)Один из дополнительных геймплейных тегов"]
color = "193, 122, 160"
condition_id = 6

[[tiles]]
pos = 24
title = "Roguelike"
description = "Ролл производится по одному из следующих тегов: Rogue-like или roguelite"
rules = ["(Теги)Rogue-like, roguelite"]
color = "16, 85, 203"
condition_id = 6

[[tiles]]
pos = 25
title = "Anime"
description = "Ролл производится по тегу Anime"
rules = ["(Теги)Anime"]
color = "255, 216, 101"
condition_id = 6

[[tiles]]
pos = 26
title = "Случайная игра"
description = "Ролится случайны рейтинг по распределению (диапазон рейтинга игры - шанс): 100-80% - 60%, 79-70% - 20%, 69-50 - 10%, 49-.. - 10%. Если игр больше чем 1000, то равномерно ролится одно значение из выпавшего диапазона. По итоговому рейтингу роллится игра"
rules = ["(Рейтинг)Полученный рейтинг"]
color = "230, 183, 174"
condition_id = 6

[[tiles]]
pos = 27
title = "Спешл"
description = "Ролл производится или по правилам тюрьма, или по правилам ТОП-100 (в зависимости от того, как игрок попал на клетку)"
rules = ["(Конкретные игры)Любая на выбор игрока"]
color = "179, 94, 5"
condition_id = 6

[[tiles]]
pos = 28
title = "Roguelike"
description = "Ролл производится по одному из следующих тегов: Rogue-like или roguelite"
rules = ["(Теги)Rogue-like, roguelite"]
color = "16, 85, 203"
condition_id = 6

[[tiles]]
pos = 29
title = "Puzzle"
description = "Ролл производится по тегу Puzzle"
rules = ["(Теги)Puzzle"]
color = "56, 117, 28"
condition_id = 6

[[tiles]]
pos = 30
title = "Anime"
description = "Ролл производится по тегу Anime"
rules = ["(Теги)Anime"]
color = "255, 216, 101"
condition_id = 6

[[tiles]]
pos = 31
title = "ТОП-100 (31)"
description = "Ролл производится из лучших 100 игр"
rules = ["(Конкретные игры)TOP-100 по steamdb рейтингу"]
color = "203, 65, 36"
condition_id = 7

[[tiles]]
pos = 32
title = "AAA"
description = "Игра ролится по цене выше 39$"
rules = ["(Цена)>39$"]
color = "141, 123, 194"
condition_id = 6

[[tiles]]
pos = 33
title = "Доп. спец. теги"
description = "Ролл производится по случайному дополнительному тегу"
rules = ["(Теги)Один из дополнительных специальных тегов"]
color = "193, 122, 160"
condition_id = 6

[[tiles]]
pos = 34
title = "RPG"
description = "Игра роллится по одному из следующих тегов: RPG, Action RPG, JRPG или Tactical RPG"
rules = ["(Теги)RPG, Action RPG, JRPG, Tactical RPG"]
color = "152, 0, 0"
condition_id = 6

[[tiles]]
pos = 35
title = "AAA"
description = "Игра ролится по цене выше 39$"
rules = ["(Цена)>39$"]
color = "141, 123, 194"
condition_id = 6

[[tiles]]
pos = 36
title = "Случайная игра"
description = "Ролится случайны рейтинг по распределению (диапазон рейтинга игры - шанс): 100-80% - 60%, 79-70% - 20%, 69-50 - 10%, 49-.. - 10%. Если игр больше чем 1000, то равномерно ролится одно значение из выпавшего диапазона. По итоговому рейтингу роллится игра"
rules = ["(Рейтинг)Полученный рейтинг"]
color = "230, 183, 174"
condition_id = 6

[[tiles]]
pos = 37
title = "Stratege"
description = "Игра роллится по одному из тегов: Strategy, Turn-Based Strategy или Strategy RPG"
rules = ["(Теги)Strategy, Turn-Based Strategy, Strategy RPG"]
color = "128, 128, 128"
condition_id = 6

[[tiles]]
pos = 38
title = "RPG"
description = "Игра роллится по одному из следующих тегов: RPG, Action RPG, JRPG или Tactical RPG"
rules = ["(Теги)RPG, Action RPG, JRPG, Tactical RPG"]
color = "152, 0, 0"
condition_id = 6

[[tiles]]
pos = 39
title = "Спешл"
description = "Ролл производится или по правилам тюрьма, или по правилам ТОП-100 (в зависимости от того, как игрок попал на клетку)"
rules = ["(Конкретные игры)Любая на выбор игрока"]
color = "193, 122, 160"
condition_id = 6

[[tiles]]
pos = 40
title = "Tactical"
description = "Игра роллится по одному из тегов: Tactical, Turn-Based Tactics или Tactical RPG"
rules = ["(Теги)Tactical, Turn-Based Tactics, Tactical RPG"]
color = "128, 128, 128"
condition_id = 6
