export struct FieldData {
	title: string,
	description: string,
	rules: [string],
	condition_id: int,
	fill_color: color,
}

export component FieldTile inherits Rectangle {
	in-out property <FieldData> field_data;

	preferred-width: 64px;
	preferred-height: 64px;

	border-width: 1px;
	border-color: black;

	TouchArea {
		clicked => {
			additional_info.show();

		}
	}

	background: field_data.fill-color;

	Text {
		text: parent.field_data.title;
		width: 100%;
		horizontal-alignment: center;
		wrap: word-wrap;
		overflow: elide;
	}

	additional_info := PopupWindow {
		x: 0;
		y: 0;

		Rectangle {
			background: white;
			Text {
				text: field_data.title;
			}
		}
	}
}
