export struct FieldData {
	title: string,
	description: string,
	rules: [string],
	condition_id: int,
	fill_color: color,
}

export component FieldTile inherits Rectangle {
	in-out property <FieldData> field_data;

	in property <length> text_size;

	preferred-width: 64px;
	preferred-height: 64px;

	border-width: 2px;
	border-color: black;

	TouchArea {
		clicked => {
			additional_info.show();

		}
	}

	background: field_data.fill_color;

	Text {
		width: parent.width;
		height: parent.height;
		text: parent.field_data.title;
		horizontal-alignment: center;
		vertical-alignment: center;
		font-size: text_size / 8;
		font-weight: 600;
		color: white;
		wrap: word-wrap;
		overflow: elide;
	}

	additional_info := PopupWindow {
		Rectangle {
			background: white;
			width: 100%;
			height: 100%;

			Text {
				padding: 100px;
				text: field_data.title;
			}
		}

		x: 0;
		y: 0;
		height: 2 * parent.height;
		width: parent.width;

	}
}
