import { FieldTilesData } from "./field_data.slint";
import { InfoPanelAdapter } from "./info_panel.slint";

export component FieldTile inherits Rectangle {
	in-out property <FieldTilesData> field_data;

	in property <length> text_size;

	preferred-width: 64px;
	preferred-height: 64px;

	border-width: 2px;
	border-color: black;

	TouchArea {
		clicked => {
			InfoPanelAdapter.tile_data = parent.field_data;
			InfoPanelAdapter.panel_mode = 1;
		}
	}

	background: field_data.fill_color;

	Text {
		width: parent.width;
		height: parent.height;
		text: parent.field_data.title;
		horizontal-alignment: center;
		vertical-alignment: center;
		font-size: text_size;
		font-weight: 600;
		color: white;
		wrap: word-wrap;
		overflow: elide;
	}

	//NOTE: since slint doesn't support dynamic position of PopUpWindow based on self size,
	// this code can be removed
	additional_info := PopupWindow {
		Rectangle {
			background: white;
			width: 100%;
			height: 100%;

			Text {
				padding: 100px;
				text: field_data.title;
			}
		}

		height: 2 * parent.height;
		width: parent.width;

		x: 0;
		y: 0;

	}
}
