import { Button } from "std-widgets.slint";

import { FieldAdapter } from "./field.slint";
import { LowerPanelAdapter } from "./adapters.slint";

export component LowerPanel inherits Rectangle {
	background: gray;
	in property <length> panel_size;
	in property <length> panel_size_width;

	if !LowerPanelAdapter.condition_button:
		HorizontalLayout {
			Rectangle {
				width: panel_size_width * 0.6;
				background: gray;
				VerticalLayout {
					alignment: space-around;
					Text {
						text: "Player status: " + LowerPanelAdapter.player_status + "; Main tag: " + LowerPanelAdapter.player_main_tag;
						color: black;
						vertical-alignment: center;
						font-size: panel_size / 6;
						font-weight: 500;
						wrap: word-wrap;
						overflow: elide;
					}
					Text {
						text: "Additional tags: " + LowerPanelAdapter.combined_add_tags;
						color: black;
						vertical-alignment: center;
						font-size: panel_size / 6;
						font-weight: 500;
						wrap: word-wrap;
						overflow: elide;
					}
					Text {
						text: "Specials: " + LowerPanelAdapter.combined_specials;
						color: black;
						vertical-alignment: center;
						font-size: panel_size / 6;
						font-weight: 500;
						wrap: word-wrap;
						overflow: elide;
					}
				}
			}

			if LowerPanelAdapter.player_status == 1:
				Button {
					text: "Roll dice";
					clicked => {
						LowerPanelAdapter.roll_dice();
					}
				}

			if LowerPanelAdapter.player_status == 2:
				Button {
					text: "Roll main tag";
					clicked => {
						LowerPanelAdapter.roll_tag();
					}
				}

			if LowerPanelAdapter.player_status == 3:
				Button {
					text: "Roll game";
					clicked => {
						LowerPanelAdapter.roll_game();
					}
				}

			if LowerPanelAdapter.player_status == 4:
				Button {
					text: "Commit used";
					clicked => {
						LowerPanelAdapter.commit_used();
					}
				}

			if LowerPanelAdapter.player_status == 5:
				Button {
					text: "Complete game";
					clicked => {
						LowerPanelAdapter.complete_game();
					}
				}

			Button {
				text: "Save";
				clicked => {
					LowerPanelAdapter.save_player_state();
				}
			}

			// To debug
			/*
			Button {
				text: "+1";
				clicked => {
					FieldAdapter.player_loc_id += 1;
					LowerPanelAdapter.update_player_state(FieldAdapter.player_loc_id)
				}
			}
			*/
		}
	
	if LowerPanelAdapter.condition_button:
		HorizontalLayout {
			Button {
				text: "Roll next condition";
				clicked => {
					LowerPanelAdapter.roll_next_condition();
				}
			}
		}
}

