import { Button } from "std-widgets.slint";

import { FieldAdapter } from "./field.slint";

export global LowerPanelAdapter {
	in-out property <bool> condition_button;

	in-out property <int> player_status;
	in-out property <string> player_main_tag;
	in-out property <[string]> player_special;
	in-out property <[string]> player_add_tags;
	in-out property <string> combined_specials;
	in-out property <string> combined_add_tags;
	
	callback update_player_state(int);
	callback roll_dice();
	callback save_player_state();
	
	callback roll_next_condition();
	callback roll_tag();
	callback roll_game();
}

export component LowerPanel inherits Rectangle {
	background: gray;
	in property <length> panel_size;

	if !LowerPanelAdapter.condition_button:
		HorizontalLayout {
			Button {
				text: "Click me: " + FieldAdapter.player_loc_id;
				clicked => {
					FieldAdapter.player_loc_id += 1;
					LowerPanelAdapter.update_player_state(FieldAdapter.player_loc_id);
				}
			}

			Rectangle {
				background: gray;
				VerticalLayout {
					alignment: space-around;
					Text {
						text: "Player status: " + LowerPanelAdapter.player_status + "; Main tag: " + LowerPanelAdapter.player_main_tag;
						color: black;
						vertical-alignment: center;
						font-size: panel_size / 6;
						font-weight: 500;
						wrap: word-wrap;
						overflow: elide;
					}
					Text {
						text: "Additional tags: " + LowerPanelAdapter.combined_add_tags;
						color: black;
						vertical-alignment: center;
						font-size: panel_size / 6;
						font-weight: 500;
						wrap: word-wrap;
						overflow: elide;
					}
					Text {
						text: "Specials: " + LowerPanelAdapter.combined_specials;
						color: black;
						vertical-alignment: center;
						font-size: panel_size / 6;
						font-weight: 500;
						wrap: word-wrap;
						overflow: elide;
					}
				}
			}

			if LowerPanelAdapter.player_status == 1:
				Button {
					text: "Roll dice";
					clicked => {
						LowerPanelAdapter.roll_dice();
					}
				}

			if LowerPanelAdapter.player_status == 2:
				Button {
					text: "Roll main tag";
					clicked => {
						LowerPanelAdapter.roll_tag();
					}
				}

			if LowerPanelAdapter.player_status == 3:
				Button {
					text: "Roll game";
					clicked => {
						LowerPanelAdapter.roll_game();
					}
				}

			Button {
				text: "Save";
				clicked => {
					LowerPanelAdapter.save_player_state();
				}
			}
		}
	
	if LowerPanelAdapter.condition_button:
		HorizontalLayout {
			Button {
				text: "Roll next condition";
				clicked => {
					LowerPanelAdapter.roll_next_condition();
				}
			}
		}
}

